name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install wasm toolchain
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      run: |
        cd contract
        ./build.sh
    - name: Run tests
      run: |
        cd contract
        ./test.sh
